<?php

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert([
            'name' => 'Admin Dashboard',
            'type' => 'main',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'admindashboard',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-speedometer',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 1,
        ]);
        DB::table('menus')->insert([
            'name' => 'Organizations',
            'type' => 'main',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'organizations',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'fa fa-sitemap',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 2,
        ]);
        DB::table('menus')->insert([
            'name' => 'Users',
            'type' => 'main',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'users',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-users',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 3,
        ]);
        DB::table('menus')->insert([
            'name' => 'Projects',
            'type' => 'main',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'projects',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-briefcase',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 4,
        ]);
        DB::table('menus')->insert([
            'name' => 'Dashboards',
            'type' => 'main',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'systemdashboards',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-speedometer',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 5,
        ]);
        DB::table('menus')->insert([
            'name' => 'Events Manager',
            'type' => 'main',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'systemevents',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'fa fa-clock-o',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 6,
        ]);
        DB::table('menus')->insert([
            'name' => 'Report Generator',
            'type' => 'main',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'systemreports',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-notebook',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 7,
        ]);
         DB::table('menus')->insert([
            'name' => 'Triggers Manager',
            'type' => 'main',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'systemtriggers',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'fa fa-flash',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 8,
        ]);
          DB::table('menus')->insert([
            'name' => 'Notifications',
            'type' => 'main',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'systemnotifications',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-bell',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 9,
        ]);

         DB::table('menus')->insert([
            'name' => 'Log out',
            'type' => 'button',
            'role_id' => 1,
            //'parent_id' => '',
            'data_ui_sref' => 'logout',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-logout',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 10,
            'ng_click' => 'logout()',
        ]);

        DB::table('menus')->insert([
            'name' => 'Home',
            'type' => 'main',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'homedashboard',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-home',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 1,

        ]);
        DB::table('menus')->insert([
            'name' => 'Organization',
            'type' => 'main',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'organizationorglist',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'fa fa-sitemap',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 2,
        ]);
        DB::table('menus')->insert([
            'name' => 'Users',
            'type' => 'main',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'users',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-users',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 3,
        ]);
        DB::table('menus')->insert([
            'name' => 'Projects',
            'type' => 'main',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'projects',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-briefcase',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 4,
        ]);
        DB::table('menus')->insert([
            'name' => 'Dashboards',
            'type' => 'main',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'organizationdashboards',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-speedometer',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 5,
        ]);
        DB::table('menus')->insert([
            'name' => 'Events',
            'type' => 'main',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'organizationevents',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'fa fa-clock-o',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 6,
        ]);
        DB::table('menus')->insert([
            'name' => 'Triggers',
            'type' => 'main',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'organizationtriggers',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'fa fa-flash',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 7,
        ]);
        DB::table('menus')->insert([
            'name' => 'Reports',
            'type' => 'main',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'organizationreports',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-notebook',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 8,
        ]);
        DB::table('menus')->insert([
            'name' => 'Notifications',
            'type' => 'main',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'organizationnotifications',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-bell',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 9,
        ]);
        DB::table('menus')->insert([
            'name' => 'Log out',
            'type' => 'button',
            'role_id' => 2,
            //'parent_id' => '',
            'data_ui_sref' => 'logout',
            'data_ui_sref_active' => 'active',
            //'data_ng_class' => '2017-04-13 02:40:09',
            //'data_toggle' => '2017-04-13 02:40:09',
            'icon_class' => 'si si-logout',
            'span_class' => 'sidebar-mini-hide',
            'active' => '1',
            'menu_order' => 10,
            'ng_click' => 'logout()',
        ]);
    }
}
